// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "api/internal/logic/audit"
	_ "api/internal/logic/audit_process"
	_ "api/internal/logic/dept"
	_ "api/internal/logic/dict_data"
	_ "api/internal/logic/dict_type"
	_ "api/internal/logic/log"
	_ "api/internal/logic/menu"
	_ "api/internal/logic/message"
	_ "api/internal/logic/post"
	_ "api/internal/logic/role"
	_ "api/internal/logic/settings"
	_ "api/internal/logic/user"
)
