// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Audit is the golang structure of table data_audit for DAO operations like Where/Data.
type Audit struct {
	g.Meta        `orm:"table:data_audit, do:true"`
	Id            interface{} // ID编号
	PlatformId    interface{} // 平台ID
	ServiceName   interface{} // 业务名称
	ServiceType   interface{} // 业务类型 1. 采购审核
	ServiceId     interface{} // 业务ID
	FinalStep     interface{} // 最终步骤
	CurrentStep   interface{} // 当前步骤
	IndexColumn   interface{} // 步骤与业务索引
	ApplyId       interface{} // 申请人ID
	AuditorId     interface{} // 审核人ID
	AuditTime     *gtime.Time // 最后一次审核时间
	AuditRemark   interface{} // 最后一次审核备注
	Remark        interface{} // 申请审核备注
	Status        interface{} // 审核状态 1 审核中 2 已通过 3 已拒绝
	DeletedStatus interface{} // 删除状态 1 正常状态 2 删除状态
	CreatedAt     *gtime.Time // 创建时间
	UpdatedAt     *gtime.Time // 更新时间
}
