// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// AuditRecord is the golang structure of table log_audit_record for DAO operations like Where/Data.
type AuditRecord struct {
	g.Meta      `orm:"table:log_audit_record, do:true"`
	Id          interface{} // ID编号
	AuditId     interface{} // 审核ID
	ServiceType interface{} // 业务类型 1. 采购审核
	ServiceId   interface{} // 业务ID
	AuditorId   interface{} // 审核人ID
	AuditRemark interface{} // 审核备注
	AuditStep   interface{} // 审核流程
	Action      interface{} // 动作 1 通过 0 拒绝
	CreatedAt   *gtime.Time // 生成时间
}
