// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// ConfigAuditProcess is the golang structure of table config_audit_process for DAO operations like Where/Data.
type ConfigAuditProcess struct {
	g.Meta            `orm:"table:config_audit_process, do:true"`
	Id                interface{} // ID编号
	Type              interface{} // 审核类型：1 通用配置 2 部门负责人
	PlatformId        interface{} // 平台ID
	ServiceName       interface{} // 业务名称
	ServiceType       interface{} // 业务类型 1. 采购审核
	AuditDepartmentId interface{} // 审核部门ID
	AuditUserId       interface{} // 用户ID（可为空，如果为空表明是这个部门下的权限）
	Procedure         interface{} // 步骤编号
}
