// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Settings is the golang structure of table data_settings for DAO operations like Where/Data.
type Settings struct {
	g.Meta    `orm:"table:data_settings, do:true"`
	Id        interface{} //
	Name      interface{} // 名称
	Value     interface{} // 内容为json
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
