// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// ConfigAuditProcessDao is the data access object for table config_audit_process.
type ConfigAuditProcessDao struct {
	table   string                    // table is the underlying table name of the DAO.
	group   string                    // group is the database configuration group name of current DAO.
	columns ConfigAuditProcessColumns // columns contains all the column names of Table for convenient usage.
}

// ConfigAuditProcessColumns defines and stores column names for table config_audit_process.
type ConfigAuditProcessColumns struct {
	Id                string // ID编号
	Type              string // 审核类型：1 通用配置 2 部门负责人
	PlatformId        string // 平台ID
	ServiceName       string // 业务名称
	ServiceType       string // 业务类型 1. 采购审核
	AuditDepartmentId string // 审核部门ID
	AuditUserId       string // 用户ID（可为空，如果为空表明是这个部门下的权限）
	Procedure         string // 步骤编号
}

// configAuditProcessColumns holds the columns for table config_audit_process.
var configAuditProcessColumns = ConfigAuditProcessColumns{
	Id:                "id",
	Type:              "type",
	PlatformId:        "platform_id",
	ServiceName:       "service_name",
	ServiceType:       "service_type",
	AuditDepartmentId: "audit_department_id",
	AuditUserId:       "audit_user_id",
	Procedure:         "procedure",
}

// NewConfigAuditProcessDao creates and returns a new DAO object for table data access.
func NewConfigAuditProcessDao() *ConfigAuditProcessDao {
	return &ConfigAuditProcessDao{
		group:   "default",
		table:   "config_audit_process",
		columns: configAuditProcessColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *ConfigAuditProcessDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *ConfigAuditProcessDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *ConfigAuditProcessDao) Columns() ConfigAuditProcessColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *ConfigAuditProcessDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *ConfigAuditProcessDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *ConfigAuditProcessDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
