// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// DictTypeDao is the data access object for table data_dict_type.
type DictTypeDao struct {
	table   string          // table is the underlying table name of the DAO.
	group   string          // group is the database configuration group name of current DAO.
	columns DictTypeColumns // columns contains all the column names of Table for convenient usage.
}

// DictTypeColumns defines and stores column names for table data_dict_type.
type DictTypeColumns struct {
	DictId    string // 字典主键
	DictName  string // 字典名称
	DictType  string // 字典类型
	Status    string // 状态（0正常 1停用）
	CreateBy  string // 创建者
	UpdateBy  string // 更新者
	Remark    string // 备注
	CreatedAt string // 创建日期
	UpdatedAt string // 修改日期
}

// dictTypeColumns holds the columns for table data_dict_type.
var dictTypeColumns = DictTypeColumns{
	DictId:    "dict_id",
	DictName:  "dict_name",
	DictType:  "dict_type",
	Status:    "status",
	CreateBy:  "create_by",
	UpdateBy:  "update_by",
	Remark:    "remark",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

// NewDictTypeDao creates and returns a new DAO object for table data access.
func NewDictTypeDao() *DictTypeDao {
	return &DictTypeDao{
		group:   "default",
		table:   "data_dict_type",
		columns: dictTypeColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *DictTypeDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *DictTypeDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *DictTypeDao) Columns() DictTypeColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *DictTypeDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *DictTypeDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *DictTypeDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
