// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"api/api/v1/admin"
	"api/internal/model"
	"context"
)

type (
	IAudit interface {
		Create(ctx context.Context, in *model.AuditCreateInput) (err error)
		Update(ctx context.Context, in *admin.AuditUpdateReq) (err error)
		Delete(ctx context.Context, in []uint) (err error)
		List(ctx context.Context, req *admin.AuditListReq) (res *admin.AuditListRes, err error)
		Detail(ctx context.Context, req *admin.AuditDetailReq) (res *admin.AuditDetailRes, err error)
	}
)

var (
	localAudit IAudit
)

func Audit() IAudit {
	if localAudit == nil {
		panic("implement not found for interface IAudit, forgot register?")
	}
	return localAudit
}

func RegisterAudit(i IAudit) {
	localAudit = i
}
