// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"api/api/v1/admin"
	"api/internal/model"
	"api/internal/model/entity"
	"context"
)

type (
	IDept interface {
		Create(ctx context.Context, in *admin.DeptCreateReq) (err error)
		Update(ctx context.Context, in *admin.DeptUpdateReq) (err error)
		Delete(ctx context.Context, in *admin.DeptDeleteReq) (err error)
		Info(ctx context.Context, in *admin.DeptInfoReq) (out *entity.Dept, err error)
		GetList(ctx context.Context, req *admin.DeptListReq) (list []*entity.Dept, err error)
		GetListCache(ctx context.Context) (list []*entity.Dept, err error)
		Tree(pid int64, list []*entity.Dept) (deptTree []*model.DeptTreeOutput)
	}
)

var (
	localDept IDept
)

func Dept() IDept {
	if localDept == nil {
		panic("implement not found for interface IDept, forgot register?")
	}
	return localDept
}

func RegisterDept(i IDept) {
	localDept = i
}
