// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"api/api/v1/admin"
	"context"
)

type (
	IDictData interface {
		Create(ctx context.Context, in *admin.DictDataCreateReq) (err error)
		Update(ctx context.Context, in *admin.DictDataUpdateReq) (err error)
		Delete(ctx context.Context, in *admin.DictDataDeleteReq) (err error)
		Show(ctx context.Context, in *admin.DictDataShowReq) (res *admin.DictDataShowRes, err error)
		List(ctx context.Context, in *admin.DictDataListReq) (res *admin.DictDataListRes, err error)
	}
)

var (
	localDictData IDictData
)

func DictData() IDictData {
	if localDictData == nil {
		panic("implement not found for interface IDictData, forgot register?")
	}
	return localDictData
}

func RegisterDictData(i IDictData) {
	localDictData = i
}
