// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"api/api/v1/admin"
	"context"
)

type (
	IDictType interface {
		Create(ctx context.Context, in *admin.DictTypeCreateReq) (err error)
		Update(ctx context.Context, in *admin.DictTypeUpdateReq) (err error)
		Delete(ctx context.Context, in *admin.DictTypeDeleteReq) (err error)
		List(ctx context.Context, in *admin.DictTypeListReq) (res *admin.DictTypeListRes, err error)
	}
)

var (
	localDictType IDictType
)

func DictType() IDictType {
	if localDictType == nil {
		panic("implement not found for interface IDictType, forgot register?")
	}
	return localDictType
}

func RegisterDictType(i IDictType) {
	localDictType = i
}
