// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"api/api/v1/admin"
	"api/internal/model/entity"
	"context"
)

type (
	IPost interface {
		List(ctx context.Context, in *admin.PostListReq) (res *admin.PostListRes, err error)
		Create(ctx context.Context, in *admin.PostCreateReq) (err error)
		Update(ctx context.Context, in *admin.PostUpdateReq) (err error)
		Delete(ctx context.Context, in *admin.PostDeleteReq) (err error)
		GetUsedPost(ctx context.Context) (list []*entity.Post, err error)
	}
)

var (
	localPost IPost
)

func Post() IPost {
	if localPost == nil {
		panic("implement not found for interface IPost, forgot register?")
	}
	return localPost
}

func RegisterPost(i IPost) {
	localPost = i
}
