// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"api/api/v1/admin"
	"api/internal/model"
	"context"
)

type (
	IRole interface {
		GetRoleListSearch(ctx context.Context, in *admin.RoleListReq) (res *admin.RoleListRes, err error)
		Create(ctx context.Context, in *admin.RoleCreateReq) (err error)
		Update(ctx context.Context, in *admin.RoleUpdateReq) (err error)
		Delete(ctx context.Context, id uint) (err error)
		CheckByNameExists(ctx context.Context, name string, id uint) bool
		AddRoleRule(ctx context.Context, ruleIds []uint, roleId int64) (err error)
		DelRoleRule(ctx context.Context, roleId uint) (err error)
		Info(ctx context.Context, id uint) (output *model.Info, err error)
		GetFilteredNamedPolicy(ctx context.Context, id uint) (gSlice []int, err error)
	}
)

var (
	localRole IRole
)

func Role() IRole {
	if localRole == nil {
		panic("implement not found for interface IRole, forgot register?")
	}
	return localRole
}

func RegisterRole(i IRole) {
	localRole = i
}
