// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"api/api/v1/admin"
	"context"
)

type (
	ISettings interface {
		Update(ctx context.Context, req *admin.SettingUpdateReq) (err error)
		Detail(ctx context.Context, req *admin.SettingDetailReq) (res *admin.SettingDetailRes, err error)
	}
)

var (
	localSettings ISettings
)

func Settings() ISettings {
	if localSettings == nil {
		panic("implement not found for interface ISettings, forgot register?")
	}
	return localSettings
}

func RegisterSettings(i ISettings) {
	localSettings = i
}
