// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"api/internal/dao/internal"
)

// internalAuditDao is internal type for wrapping internal DAO implements.
type internalAuditDao = *internal.AuditDao

// auditDao is the data access object for table data_audit.
// You can define custom methods on it to extend its functionality as you wish.
type auditDao struct {
	internalAuditDao
}

var (
	// Audit is globally public accessible object for table data_audit operations.
	Audit = auditDao{
		internal.NewAuditDao(),
	}
)

// Fill with you ideas below.
