// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"api/internal/dao/internal"
)

// internalAuditRecordDao is internal type for wrapping internal DAO implements.
type internalAuditRecordDao = *internal.AuditRecordDao

// auditRecordDao is the data access object for table log_audit_record.
// You can define custom methods on it to extend its functionality as you wish.
type auditRecordDao struct {
	internalAuditRecordDao
}

var (
	// AuditRecord is globally public accessible object for table log_audit_record operations.
	AuditRecord = auditRecordDao{
		internal.NewAuditRecordDao(),
	}
)

// Fill with you ideas below.
