// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"api/internal/dao/internal"
)

// internalConfigAuditProcessDao is internal type for wrapping internal DAO implements.
type internalConfigAuditProcessDao = *internal.ConfigAuditProcessDao

// configAuditProcessDao is the data access object for table config_audit_process.
// You can define custom methods on it to extend its functionality as you wish.
type configAuditProcessDao struct {
	internalConfigAuditProcessDao
}

var (
	// ConfigAuditProcess is globally public accessible object for table config_audit_process operations.
	ConfigAuditProcess = configAuditProcessDao{
		internal.NewConfigAuditProcessDao(),
	}
)

// Fill with you ideas below.
