// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"api/internal/dao/internal"
)

// internalDictTypeDao is internal type for wrapping internal DAO implements.
type internalDictTypeDao = *internal.DictTypeDao

// dictTypeDao is the data access object for table data_dict_type.
// You can define custom methods on it to extend its functionality as you wish.
type dictTypeDao struct {
	internalDictTypeDao
}

var (
	// DictType is globally public accessible object for table data_dict_type operations.
	DictType = dictTypeDao{
		internal.NewDictTypeDao(),
	}
)

// Fill with you ideas below.
