// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"api/internal/dao/internal"
)

// internalOperLogDao is internal type for wrapping internal DAO implements.
type internalOperLogDao = *internal.OperLogDao

// operLogDao is the data access object for table data_oper_log.
// You can define custom methods on it to extend its functionality as you wish.
type operLogDao struct {
	internalOperLogDao
}

var (
	// OperLog is globally public accessible object for table data_oper_log operations.
	OperLog = operLogDao{
		internal.NewOperLogDao(),
	}
)

// Fill with you ideas below.
