// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"api/internal/dao/internal"
)

// internalPostDao is internal type for wrapping internal DAO implements.
type internalPostDao = *internal.PostDao

// postDao is the data access object for table data_post.
// You can define custom methods on it to extend its functionality as you wish.
type postDao struct {
	internalPostDao
}

var (
	// Post is globally public accessible object for table data_post operations.
	Post = postDao{
		internal.NewPostDao(),
	}
)

// Fill with you ideas below.
