// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"api/internal/dao/internal"
)

// internalUserPostDao is internal type for wrapping internal DAO implements.
type internalUserPostDao = *internal.UserPostDao

// userPostDao is the data access object for table data_user_post.
// You can define custom methods on it to extend its functionality as you wish.
type userPostDao struct {
	internalUserPostDao
}

var (
	// UserPost is globally public accessible object for table data_user_post operations.
	UserPost = userPostDao{
		internal.NewUserPostDao(),
	}
)

// Fill with you ideas below.
