// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Audit is the golang structure for table audit.
type Audit struct {
	Id            uint        `json:"id"             description:"ID编号"`
	PlatformId    uint        `json:"platform_id"    description:"平台ID"`
	ServiceName   string      `json:"service_name"   description:"业务名称"`
	ServiceType   int         `json:"service_type"   description:"业务类型 1. 采购审核"`
	ServiceId     string      `json:"service_id"     description:"业务ID"`
	FinalStep     int         `json:"final_step"     description:"最终步骤"`
	CurrentStep   int         `json:"current_step"   description:"当前步骤"`
	IndexColumn   string      `json:"index_column"   description:"步骤与业务索引"`
	ApplyId       string      `json:"apply_id"       description:"申请人ID"`
	AuditorId     string      `json:"auditor_id"     description:"审核人ID"`
	AuditTime     *gtime.Time `json:"audit_time"     description:"最后一次审核时间"`
	AuditRemark   string      `json:"audit_remark"   description:"最后一次审核备注"`
	Remark        string      `json:"remark"         description:"申请审核备注"`
	Status        uint        `json:"status"         description:"审核状态 1 审核中 2 已通过 3 已拒绝"`
	DeletedStatus int         `json:"deleted_status" description:"删除状态 1 正常状态 2 删除状态"`
	CreatedAt     *gtime.Time `json:"created_at"     description:"创建时间"`
	UpdatedAt     *gtime.Time `json:"updated_at"     description:"更新时间"`
}
