// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// AuditRecord is the golang structure for table audit_record.
type AuditRecord struct {
	Id          uint        `json:"id"           description:"ID编号"`
	AuditId     uint        `json:"audit_id"     description:"审核ID"`
	ServiceType int         `json:"service_type" description:"业务类型 1. 采购审核"`
	ServiceId   string      `json:"service_id"   description:"业务ID"`
	AuditorId   string      `json:"auditor_id"   description:"审核人ID"`
	AuditRemark string      `json:"audit_remark" description:"审核备注"`
	AuditStep   string      `json:"audit_step"   description:"审核流程"`
	Action      int         `json:"action"       description:"动作 1 通过 0 拒绝"`
	CreatedAt   *gtime.Time `json:"created_at"   description:"生成时间"`
}
