// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Config is the golang structure for table config.
type Config struct {
	ConfigId    uint        `json:"config_id"    description:"参数主键"`
	ConfigName  string      `json:"config_name"  description:"参数名称"`
	ConfigKey   string      `json:"config_key"   description:"参数键名"`
	ConfigValue string      `json:"config_value" description:"参数键值"`
	ConfigType  int         `json:"config_type"  description:"系统内置（Y是 N否）"`
	CreateBy    uint        `json:"create_by"    description:"创建者"`
	UpdateBy    uint        `json:"update_by"    description:"更新者"`
	Remark      string      `json:"remark"       description:"备注"`
	CreatedAt   *gtime.Time `json:"created_at"   description:"创建时间"`
	UpdatedAt   *gtime.Time `json:"updated_at"   description:"修改时间"`
}
