// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// ConfigAuditProcess is the golang structure for table config_audit_process.
type ConfigAuditProcess struct {
	Id                uint   `json:"id"                  description:"ID编号"`
	Type              uint   `json:"type"                description:"审核类型：1 通用配置 2 部门负责人"`
	PlatformId        string `json:"platform_id"         description:"平台ID"`
	ServiceName       string `json:"service_name"        description:"业务名称"`
	ServiceType       int    `json:"service_type"        description:"业务类型 1. 采购审核"`
	AuditDepartmentId int    `json:"audit_department_id" description:"审核部门ID"`
	AuditUserId       string `json:"audit_user_id"       description:"用户ID（可为空，如果为空表明是这个部门下的权限）"`
	Procedure         int    `json:"procedure"           description:"步骤编号"`
}
