// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// DictType is the golang structure for table dict_type.
type DictType struct {
	DictId    uint64      `json:"dict_id"    description:"字典主键"`
	DictName  string      `json:"dict_name"  description:"字典名称"`
	DictType  string      `json:"dict_type"  description:"字典类型"`
	Status    uint        `json:"status"     description:"状态（0正常 1停用）"`
	CreateBy  uint        `json:"create_by"  description:"创建者"`
	UpdateBy  uint        `json:"update_by"  description:"更新者"`
	Remark    string      `json:"remark"     description:"备注"`
	CreatedAt *gtime.Time `json:"created_at" description:"创建日期"`
	UpdatedAt *gtime.Time `json:"updated_at" description:"修改日期"`
}
