// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Settings is the golang structure for table settings.
type Settings struct {
	Id        int         `json:"id"         description:""`
	Name      string      `json:"name"       description:"名称"`
	Value     string      `json:"value"      description:"内容为json"`
	CreatedAt *gtime.Time `json:"created_at" description:""`
	UpdatedAt *gtime.Time `json:"updated_at" description:""`
}
