// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// UserPost is the golang structure for table user_post.
type UserPost struct {
	UserId int64 `json:"user_id" description:"用户ID"`
	PostId int64 `json:"post_id" description:"岗位ID"`
}
